CREATE TABLE table_locks (
    lock_ts TIMESTAMPTZ,
    dbname TEXT,
    waiting_pid INT,
    wait_xid TEXT,
    locked_pid INT,
    locked_xid TEXT,
    locked_relation TEXT,
    waiting_type TEXT,
    waiting_mode TEXT,
    waiting_tuple TEXT,
    locked_type TEXT,
    locked_mode TEXT,
    locked_tuple TEXT,
    waiting_app TEXT,
    waiting_addr TEXT,
    waiting_xact_start TIMESTAMPTZ,
    waiting_query_start TIMESTAMPTZ,
    waiting_start TIMESTAMPTZ,
    waiting_query TEXT,
    locked_app TEXT,
    locked_addr TEXT,
    locked_xact_start TIMESTAMPTZ,
    locked_query_start TIMESTAMPTZ,
    locked_state TEXT,
    locked_state_start TIMESTAMPTZ,
    locked_last_query TEXT
);
        
CREATE TABLE transaction_locks (
    lock_ts TIMESTAMPTZ,
    dbname TEXT,
    waiting_pid INT,
    waiting_xid TEXT,
    locked_pid INT,
    waiting_app TEXT,
    waiting_addr TEXT,
    waiting_xact_start TIMESTAMPTZ,
    waiting_query_start TIMESTAMPTZ,
    waiting_start TIMESTAMPTZ,
    waiting_query TEXT,
    locked_app TEXT,
    locked_addr TEXT,
    locked_xact_start TIMESTAMPTZ,
    locked_query_start TIMESTAMPTZ,
    locked_state TEXT,
    locked_state_start TIMESTAMPTZ,
    locked_last_query TEXT,
    waiting_relations TEXT[],
    waiting_modes TEXT[],
    waiting_lock_types TEXT[],
    locked_relations TEXT[],
    locked_modes TEXT[],
    locked_lock_types TEXT[]
);


